#
#		Makefile のコア依存部（ARM用）
# 
#  $Id: Makefile.core 876 2013-02-18 14:24:58Z ertl-hiro $
#

#
#  コア依存部ディレクトリ名の定義
#
COREDIR = $(SRCDIR)/arch/$(PRC)_$(TOOL)/common

#
#  ツール依存部ディレクトリ名の定義 
#
TOOLDIR = $(SRCDIR)/arch/$(TOOL)

#
#  パス3を使用する
#
USE_CFG_PASS3 = true

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(COREDIR) -I$(TOOLDIR)
ifdef USE_CFG_PASS3
	COPTS := $(COPTS) -DUSE_CFG_PASS3
endif
LIBS := $(LIBS) -lgcc

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR) $(COREDIR)
# DEF_HRP2_ONLY
KERNEL_ASMOBJS += core_support_hrp2.o
# END_HRP2_ONLY
# DEF_ASP_ONLY
# KERNEL_ASMOBJS += core_support_asp.o
# END_ASP_ONLY
KERNEL_COBJS := $(KERNEL_COBJS) core_config.o arm.o
KERNEL_CFLAGS := $(KERNEL_CFLAGS) -DSUPPORT_XLOG_SYS

#
#  コンフィギュレータ関係の変数の定義
#
# DEF_HRP2_ONLY
CORE_DEF_CSV := $(COREDIR)/core_def_hrp2.csv
# END_HRP2_ONLY
# DEF_ASP_ONLY
# CORE_DEF_CSV := $(COREDIR)/core_def_asp.csv
# END_ASP_ONLY
CFG_TABS := $(CFG_TABS) --cfg1-def-table $(CORE_DEF_CSV)

#
#  オフセットファイル生成のための定義
#
OFFSET_TF = $(COREDIR)/core_offset.tf

#
#  依存関係の定義
#
cfg1_out.c: $(CORE_DEF_CSV)
kernel_cfg.timestamp: $(COREDIR)/core.tf
kernel_mem3.c: $(COREDIR)/core_opt.tf
kernel_mem.c: $(COREDIR)/core_mem.tf
